apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-of-hubs-agent
  namespace: open-cluster-management
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hub-of-hubs-agent
  template:
    metadata:
      labels:
        name: hub-of-hubs-agent
    spec:
      serviceAccountName: hub-of-hubs-agent
      containers:
        - name: hub-of-hubs-agent
          image: quay.io/open-cluster-management-hub-of-hubs/hub-of-hubs-agent:latest
          args:
            - '--zap-devel=true'
            - --pod-namespace=$(POD_NAMESPACE)
            - --leaf-hub-name=$LH_ID
            - --enforce-hoh-rbac=$ENFORCE_HOH_RBAC
            - --transport-type=$TRANSPORT_TYPE
            - --kafka-bootstrap-server=$KAFKA_BOOTSTRAP_SERVERS
            - --kafka-ssl-ca=$KAFKA_SSL_CA
          imagePullPolicy: Always
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                 apiVersion: v1
                 fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                 apiVersion: v1
                 fieldPath: metadata.namespace
