kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub-of-hubs-agent
  namespace: {{ .HostedClusterName }}
subjects:
- kind: ServiceAccount
  name: hub-of-hubs-agent
  namespace: {{ .HostedClusterName }}
roleRef:
  kind: Role
  name: hub-of-hubs-agent
  apiGroup: rbac.authorization.k8s.io
