kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub-of-hubs-agent
subjects:
- kind: ServiceAccount
  name: hub-of-hubs-agent
  namespace: {{ .HostedClusterName }}
roleRef:
  kind: ClusterRole
  name: hub-of-hubs-agent
  apiGroup: rbac.authorization.k8s.io