apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hub-of-hubs-agent
  namespace: {{ .HostedClusterName }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
